#!/bin/sh
DOTFILES="$(realpath "$(dirname $0)")"
find "${DOTFILES}" -mindepth 1 -maxdepth 1 \! -name .git \! -name .config \! -name setup -print0 | xargs -0 -I{} -- ln -s {} "${HOME}"
find "${DOTFILES}/.config" -mindepth 1 -maxdepth 1 -print0 | xargs -0 -I{} -- ln -s {} "${HOME}/.config"
